"""The host asked for a file only its discarded return value locates.

``save_publication_figure`` writes the figure exports AND a
``<stem>.figure_contract.json``, and returns a ``{format: path}`` mapping whose
``"contract"`` key is the only place that JSON's path is published. The Coder
prompt showed the call with its return thrown away and then said, further down,
"Also write the ``.figure_contract.json`` generated by
``save_publication_figure``".

Measured 2026-08-01 over every generated script on disk: 53 of the 56 that call
it discard the return; 3 keep it. canary38 is what that costs. E1 reached 11 of
12 steps and the one blocked step was a figure whose script read
``figure_contract`` at a line where nothing bound it -- the mechanical preflight
refused it, correctly, and the run could not complete.

The same block named the wrong export-QA helper. ``audit_publication_exports``
returns host model objects; ``audit_publication_exports_json`` returns JSON
primitives, and its own docstring records why the converted form was published:
the prompt routes these findings into ``step_summary.json``, where the typed
form cannot be serialized, and two Coders invented incompatible conversions.
The import line still named the typed one. Measured over the same corpus: 25
scripts use the typed form, 21 use the JSON form.
"""

from __future__ import annotations

import inspect
from pathlib import Path

from easyicu.research_agent.agents.core import _build_planner_user_prompt  # noqa: F401
from easyicu.research_agent.figures import publication

_CODER_PROMPT = (
    Path(__file__).resolve().parents[2]
    / "src"
    / "easyicu"
    / "research_agent"
    / "providers"
    / "prompts"
    / "v1"
    / "coder.txt"
)


def _prompt() -> str:
    return _CODER_PROMPT.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# What the helper really does
# ---------------------------------------------------------------------------


def test_the_contract_path_is_only_reachable_through_the_return_value():
    """Anchored on the helper's source, so a rename breaks this test.

    If the key ever stops being ``contract``, the prompt sentence naming it is
    wrong and must fail here rather than in a generated script.
    """

    source = inspect.getsource(publication.save_publication_figure)

    assert 'saved["contract"] = contract_path' in source
    assert ".figure_contract.json" in source


def test_the_helper_returns_a_mapping_not_none():
    """A discarded return is only harmless if there is nothing in it."""

    signature = inspect.signature(publication.save_publication_figure)

    assert signature.return_annotation != inspect.Signature.empty
    assert "Dict" in str(signature.return_annotation)


def test_both_export_audit_forms_exist_and_only_one_is_json_safe():
    """The reason the import line matters at all."""

    assert hasattr(publication, "audit_publication_exports")
    assert hasattr(publication, "audit_publication_exports_json")

    json_form = inspect.signature(publication.audit_publication_exports_json)
    typed_form = inspect.signature(publication.audit_publication_exports)
    assert "Dict" in str(json_form.return_annotation)
    assert "ValidationFinding" in str(typed_form.return_annotation)


# ---------------------------------------------------------------------------
# What the prompt now says
# ---------------------------------------------------------------------------


def test_the_prompt_keeps_the_return_value():
    """The example call is what the model copies."""

    text = _prompt()

    assert "saved = save_publication_figure(" in text
    assert "KEEP ITS RETURN VALUE" in text


def test_the_prompt_names_the_contract_key():
    """Naming the file without naming its key is what made the model guess."""

    text = _prompt()

    assert 'saved["contract"]' in text
    assert ".figure_contract.json" in text


def test_the_prompt_forbids_the_two_ways_the_model_actually_failed():
    """String-building the stem, and reading an unbound contract name."""

    text = _prompt()

    assert "do not reconstruct them by string-building a stem" in text
    assert "do not\n  reference a contract variable you never bound" in text


def test_the_import_line_names_the_json_safe_audit():
    """25 recorded scripts imported the form that cannot be serialized."""

    text = _prompt()
    imports = text[
        text.index("from easyicu.research_agent.figures.publication import") :
    ][:400]

    assert "audit_publication_exports_json" in imports
    assert "save_publication_figure, audit_publication_exports`" not in imports


def test_the_prompt_says_why_the_typed_form_is_wrong_here():
    """A bare swap teaches nothing; the reason is what survives a rewrite."""

    text = _prompt()

    assert "cannot serialize" in text
    assert "step_summary.json must hold JSON primitives" in text.replace("\n  ", " ")


def test_the_guidance_carries_no_case_specific_token():
    """Prompt hygiene: a host-helper fact, not a benchmark fact."""

    text = _prompt()
    window = text[text.index("KEEP ITS RETURN VALUE") - 800 :][:1600].casefold()
    for token in ("sep3", "kdigo", "aki_stage", "mimic", "sepsis", "lactate"):
        assert token not in window, token
