#!/usr/bin/env python3
"""EX-A02: republish an extracted full-six candidate under a newer contract.

This command is for publication-only corrections.  It never rereads a raw ICU
database and never mutates the source run.  The destination is a new candidate
whose Parquet files, metadata sidecars, and native manifests are regenerated by
the current clean EasyICU checkout.  Provenance preserves both the original
extraction commit and the publication commit; extraction timings remain those
of the original run.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
SOURCE_ROOT = REPOSITORY_ROOT / "src"
if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))

from easyicu.api import extraction as extraction_api  # noqa: E402


DATABASES = ("aumc", "eicu", "hirid", "mimic", "miiv", "sic")
MODULES = tuple(extraction_api.EXTRACT_MODULE_ORDER)
SCHEMA_VERSION = "easyicu_full6_republication_v1"


class RepublicationError(ValueError):
    """Raised before an unsafe or provenance-incomplete republication."""


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _read_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RepublicationError(f"Cannot read JSON object {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise RepublicationError(f"Expected one JSON object: {path}")
    return value


def _atomic_write_json(path: Path, value: dict[str, Any]) -> None:
    payload = (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode()
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary = Path(handle.name)
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _rebind_extraction_timing_receipts(
    path: Path, native_manifests: dict[str, dict[str, Any]]
) -> None:
    """Bind original runtime measurements to the republished package bytes."""
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
        fieldnames = list(reader.fieldnames or [])
    required_fields = {"database", "total_rows", "total_parquet_bytes"}
    if not required_fields.issubset(fieldnames):
        raise RepublicationError(
            "Extraction timing CSV lacks republication receipt columns: "
            f"{sorted(required_fields - set(fieldnames))}"
        )
    by_database = {row.get("database"): row for row in rows}
    if len(rows) != len(DATABASES) or set(by_database) != set(DATABASES):
        raise RepublicationError(
            "Extraction timing CSV must contain exactly one row per database"
        )
    for database in DATABASES:
        files = native_manifests[database].get("files")
        if not isinstance(files, list) or len(files) != len(MODULES):
            raise RepublicationError(
                f"{database}: republished manifest lacks 19 file receipts"
            )
        by_database[database]["total_rows"] = str(
            sum(int(entry["rows"]) for entry in files)
        )
        by_database[database]["total_parquet_bytes"] = str(
            sum(int(entry["parquet_bytes"]) for entry in files)
        )

    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            newline="",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary = Path(handle.name)
            writer = csv.DictWriter(handle, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _git_output(*args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=REPOSITORY_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode:
        raise RepublicationError(
            f"git {' '.join(args)} failed: {(result.stderr or result.stdout).strip()}"
        )
    return result.stdout.strip()


def _require_clean_checkout() -> str:
    dirty = _git_output("status", "--porcelain", "--untracked-files=all")
    if dirty:
        raise RepublicationError(
            "Republication requires one clean EasyICU checkout; commit or remove "
            f"these changes first:\n{dirty}"
        )
    commit = _git_output("rev-parse", "HEAD")
    if len(commit) != 40:
        raise RepublicationError(f"Expected a full Git commit SHA, got {commit!r}")
    return commit


def _validate_source(source_run_root: Path) -> dict[str, Any]:
    if source_run_root.is_symlink() or not source_run_root.is_dir():
        raise RepublicationError(
            f"Source run must be a regular directory: {source_run_root}"
        )
    run_manifest_path = source_run_root / "run_manifest.json"
    timing_path = source_run_root / "database_extraction_timing.csv"
    if not run_manifest_path.is_file() or run_manifest_path.is_symlink():
        raise RepublicationError(f"Missing source run manifest: {run_manifest_path}")
    if not timing_path.is_file() or timing_path.is_symlink():
        raise RepublicationError(f"Missing extraction timing: {timing_path}")
    source_manifest = _read_json(run_manifest_path)
    export_root = source_run_root / "exports"
    if {path.name for path in export_root.iterdir() if path.is_dir()} != set(
        DATABASES
    ):
        raise RepublicationError("Source exports do not contain exactly six databases")
    for database in DATABASES:
        database_root = export_root / database
        native_manifest = database_root / "_manifest.json"
        if not native_manifest.is_file() or native_manifest.is_symlink():
            raise RepublicationError(f"Missing native manifest: {native_manifest}")
        for module in MODULES:
            parquet = database_root / f"{module}.parquet"
            producer_manifest = database_root / f"{module}.manifest.json"
            if not parquet.is_file() or parquet.is_symlink():
                raise RepublicationError(f"Missing regular source file: {parquet}")
            if not producer_manifest.is_file() or producer_manifest.is_symlink():
                raise RepublicationError(
                    f"Missing producer manifest needed for republication: "
                    f"{producer_manifest}"
                )
    return source_manifest


def _hardlink_or_copy(source: str, destination: str) -> str:
    try:
        os.link(source, destination)
        return destination
    except OSError:
        return shutil.copy2(source, destination)


def _clone_source(source: Path, destination: Path) -> None:
    if destination.exists() or destination.is_symlink():
        raise RepublicationError(
            f"Destination must not already exist: {destination}"
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(
        source,
        destination,
        symlinks=False,
        copy_function=_hardlink_or_copy,
    )


def _source_database_receipt(database_root: Path) -> dict[str, Any]:
    manifest_path = database_root / "_manifest.json"
    manifest = _read_json(manifest_path)
    runtime = manifest.get("runtime_provenance") or {}
    return {
        "native_manifest_sha256": _sha256_file(manifest_path),
        "easyicu_git_commit": runtime.get("easyicu_git_commit"),
        "easyicu_git_dirty": runtime.get("easyicu_git_dirty"),
    }


def _republish_database(
    database_root: Path,
    *,
    database: str,
    source_receipt: dict[str, Any],
    publication_commit: str,
) -> dict[str, Any]:
    old_manifest = database_root / "_manifest.json"
    old_payload = _read_json(old_manifest)
    sidecar = old_payload.get("column_metadata") or {}
    sidecar_name = sidecar.get("file")
    old_manifest.unlink()
    if isinstance(sidecar_name, str) and sidecar_name:
        (database_root / sidecar_name).unlink(missing_ok=True)
    for stale in database_root.glob("column_metadata.sha256-*.json"):
        stale.unlink()

    extraction_api._publish_native_export_v2(
        database=database,
        data_path=str(old_payload.get("data_path") or "publication-only"),
        output_dir=str(database_root),
        modules=list(MODULES),
        max_patients=old_payload.get("max_patients"),
        result={
            "modules": {module: {"errors": []} for module in MODULES}
        },
    )
    new_manifest = _read_json(old_manifest)
    new_manifest["source_extraction_provenance"] = {
        **source_receipt,
        "publication_only": True,
        "raw_database_reread": False,
        "publication_easyicu_git_commit": publication_commit,
        "transformation": (
            "canonical native-v2 republication from the source candidate's "
            "already extracted module Parquet files"
        ),
    }
    _atomic_write_json(old_manifest, new_manifest)
    return new_manifest


def republish_candidate(source_run_root: Path, output_root: Path) -> Path:
    source = source_run_root.resolve()
    destination = output_root.absolute()
    if source == destination:
        raise RepublicationError("Source and destination must be different")
    publication_commit = _require_clean_checkout()
    source_run_manifest = _validate_source(source)
    source_run_manifest_sha256 = _sha256_file(source / "run_manifest.json")
    source_receipts = {
        database: _source_database_receipt(source / "exports" / database)
        for database in DATABASES
    }

    try:
        _clone_source(source, destination)
        # A republication is never verified merely because the source happened
        # to be sealed.  EX-A01 must validate the new bytes and create fresh
        # release evidence after this command completes.
        (destination / "run_metadata.json").unlink(missing_ok=True)
        (destination / "module_extraction_timing.csv").unlink(missing_ok=True)
        new_manifests = {
            database: _republish_database(
                destination / "exports" / database,
                database=database,
                source_receipt=source_receipts[database],
                publication_commit=publication_commit,
            )
            for database in DATABASES
        }
        _rebind_extraction_timing_receipts(
            destination / "database_extraction_timing.csv", new_manifests
        )
        provenance = {
            "schema_version": SCHEMA_VERSION,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "source_run_root": str(source),
            "source_run_manifest_sha256": source_run_manifest_sha256,
            "source_database_receipts": source_receipts,
            "publication_easyicu_git_commit": publication_commit,
            "publication_easyicu_git_dirty": False,
            "republisher": str(Path(__file__).relative_to(REPOSITORY_ROOT)),
            "republisher_sha256": _sha256_file(Path(__file__)),
            "raw_database_reread": False,
            "timing_runtime_measurements_preserved": True,
            "timing_package_receipts_rebound": True,
            "database_count": len(DATABASES),
            "module_count": len(MODULES),
        }
        _atomic_write_json(destination / "republication_provenance.json", provenance)

        updated_run_manifest = dict(source_run_manifest)
        updated_run_manifest["release_republication"] = provenance
        updated_run_manifest["publication_checkout"] = {
            "easyicu_git_commit": publication_commit,
            "easyicu_git_dirty": False,
        }
        for database, native_manifest in new_manifests.items():
            source_record = (updated_run_manifest.get("sources") or {}).get(database)
            if not isinstance(source_record, dict):
                continue
            source_record["native_publication_easyicu_git_commit"] = (
                publication_commit
            )
            metrics = source_record.get("module_metrics")
            if not isinstance(metrics, dict):
                continue
            for entry in native_manifest.get("files") or []:
                module = entry.get("module")
                if module not in metrics or not isinstance(metrics[module], dict):
                    continue
                metrics[module].update(
                    {
                        "rows": entry.get("rows"),
                        "parquet_bytes": entry.get("parquet_bytes"),
                        "parquet_sha256": entry.get("parquet_sha256"),
                    }
                )
        _atomic_write_json(destination / "run_manifest.json", updated_run_manifest)
    except Exception:
        # A failed destination is intentionally retained for diagnosis.  It has
        # no run_metadata.json and cannot be promoted by EX-A01.
        raise
    return destination


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-run-root", required=True, type=Path)
    parser.add_argument("--output-root", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = republish_candidate(args.source_run_root, args.output_root)
    print(f"Republished full-six candidate: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
