"""Declarative ownership map for the EasyICU top-level import surface.

The package root uses this table for PEP 562 lazy attribute loading.  Keeping
the table separate makes ``easyicu.__init__`` a small import router instead of
an eager second implementation of every domain package.
"""

from __future__ import annotations

from typing import Final

ExportTarget = tuple[str, str]


# These are the supported, documented entry points that new code should prefer.
STABLE_EXPORTS: Final[tuple[str, ...]] = (
    "load_concepts",
    "load_sofa",
    "load_sofa2",
    "load_sepsis3",
    "ICUDataSource",
    "ResearchAgentPipeline",
    "PipelineConfig",
    "PipelineServices",
    "configure_runtime",
    "clear_easyicu_cache",
)


# EasyICU 1.x historically re-exported a broad ricu-shaped surface.  It remains
# import-compatible until 2.0, but each name resolves from its real owner only
# when used.  New features must not be added here merely for convenience.
_EXPORT_GROUPS: Final[dict[str, tuple[str, ...]]] = {
    "easyicu.api": (
        "load_medications",
        "load_concept_cached",
        "load_sofa_with_score",
    ),
    "easyicu.api.cohort": ("PatientIdDiscoveryError",),
    "easyicu.api.compat": ("align_to_icu_admission",),
    "easyicu.api.concepts": ("load_concepts", "load_concept"),
    "easyicu.api.convenience": (
        "load_sofa",
        "load_sofa2",
        "load_sepsis3",
        "load_vitals",
        "load_labs",
        "load_demographics",
        "load_outcomes",
        "load_vitals_detailed",
        "load_neurological",
        "load_output",
        "load_respiratory",
        "load_lab_comprehensive",
        "load_blood_gas",
        "load_hematology",
    ),
    "easyicu.api.medications": (
        "MedicationLoadError",
        "MedicationMergeError",
    ),
    "easyicu.api.special_concepts": (
        "list_available_concepts",
        "list_available_sources",
        "get_concept_info",
    ),
    "easyicu.callbacks": (
        "UnsupportedClinicalScoreError",
        "sofa_score",
        "sofa_resp",
        "sofa_coag",
        "sofa_liver",
        "sofa_cardio",
        "sofa_cns",
        "sofa_renal",
        "sirs_score",
        "qsofa_score",
        "apache_ii_score",
        "news_score",
        "mews_score",
        "pafi",
        "safi",
    ),
    "easyicu.concept": ("ConceptResolver",),
    "easyicu.concept.builder": (
        "new_concept",
        "new_item",
        "new_itm",
        "new_cncpt",
        "init_cncpt",
        "init_itm",
        "is_cncpt",
        "is_concept",
        "is_item",
        "is_itm",
        "new_src_tbl",
    ),
    "easyicu.concept.schema": ("ConceptDictionary",),
    "easyicu.concept.utils": (
        "add_concept",
        "concept_availability",
        "explain_dictionary",
        "subset_src",
    ),
    "easyicu.config": ("DataSourceConfig", "DataSourceRegistry"),
    "easyicu.datasource": (
        "FilterOp",
        "FilterSpec",
        "ICUDataSource",
        "load_table",
    ),
    "easyicu.io.data_converter": ("DataConverter", "ensure_database_ready"),
    "easyicu.io.data_env": (
        "SrcEnv",
        "DataEnv",
        "attached_srcs",
        "get_src_env",
        "attach_src",
        "detach_src",
        "detach_all_srcs",
        "src_env_available",
        "new_src_env",
        "src_env_objects",
        "is_src_env",
    ),
    "easyicu.io.data_load": (
        "load_src",
        "load_difftime",
        "load_id",
        "load_ts",
        "load_win",
    ),
    "easyicu.io.data_quality": (
        "DataQualityValidator",
        "validate_data_quality",
        "print_quality_summary",
    ),
    "easyicu.io.data_tools": (
        "unmerge",
        "rm_na",
        "change_dur_unit",
        "has_no_gaps",
        "load_src_cfg",
    ),
    "easyicu.io.data_utils": (
        "add_column",
        "aggregate_table",
        "change_id_type",
        "drop_columns",
        "filter_table",
        "merge_tables",
        "pivot_table",
        "rename_columns",
        "select_columns",
        "sort_table",
    ),
    "easyicu.io.download": ("download_src", "download_sources"),
    "easyicu.io.export": (
        "write_psv",
        "read_psv",
        "export_wide_format",
        "export_long_format",
        "export_summary",
        "export_cohort_info",
        "export_parquet",
        "export_feather",
        "export_json",
        "export_data",
        "data_quality_report",
    ),
    "easyicu.io.id_mapping": (
        "id_windows",
        "id_origin",
        "id_map",
        "id_map_helper",
        "id_orig_helper",
        "id_win_helper",
    ),
    "easyicu.io.import_data": ("import_src", "import_sources"),
    "easyicu.io.src_utils": (
        "src_name",
        "src_prefix",
        "src_extra_cfg",
        "src_data_avail",
        "src_tbl_avail",
        "is_data_avail",
        "is_tbl_avail",
        "is_src_tbl",
    ),
    "easyicu.io.ts_utils": (
        "change_interval",
        "expand_intervals",
        "expand",
        "collapse",
        "fill_gaps",
        "replace_na",
        "slide",
        "slide_index",
        "hop",
        "has_gaps",
        "is_regular",
        "hours",
        "minutes",
        "mins",
        "days",
        "secs",
        "weeks",
        "slide_windows",
        "stay_windows",
        "calc_dur",
        "remove_gaps",
        "merge_ranges",
        "group_measurements",
        "create_intervals",
    ),
    "easyicu.load_concepts": ("ConceptLoader",),
    "easyicu.resources": (
        "load_data_sources",
        "load_dictionary",
        "package_path",
    ),
    "easyicu.runtime.cache_manager": (
        "get_cache_manager",
        "clear_easyicu_cache",
        "get_cache_status",
    ),
    "easyicu.runtime.configure": ("configure_runtime",),
    "easyicu.runtime.memory_optimizer": (
        "MemoryMonitor",
        "MemoryConfig",
        "MemoryEfficientTable",
        "get_memory_monitor",
        "optimize_for_16gb",
    ),
    "easyicu.research_agent.pipeline": ("ResearchAgentPipeline",),
    "easyicu.research_agent.orchestration.config": ("PipelineConfig",),
    "easyicu.research_agent.orchestration.services": ("PipelineServices",),
    "easyicu.scores.sepsis": (
        "sep3",
        "susp_inf",
        "delta_cummin",
        "delta_start",
        "delta_min",
    ),
    "easyicu.scores.sepsis_sofa2": ("sep3_sofa2", "label_sep3_sofa2"),
    "easyicu.scores.sofa2": (
        "SOFA2InputError",
        "sofa2_score",
        "sofa2_resp",
        "sofa2_coag",
        "sofa2_liver",
        "sofa2_cardio",
        "sofa2_cns",
        "sofa2_cns_proxy_sensitivity",
        "sofa2_cns_delirium_tx_ascertainment",
        "sofa2_cns_ascertainment",
        "sofa2_renal",
    ),
    "easyicu.table": (
        "ICUTable",
        "IdTbl",
        "TsTbl",
        "WinTbl",
        "PvalTbl",
        "rbind_tbl",
        "cbind_tbl",
        "merge_lst",
        "is_id_tbl",
        "is_ts_tbl",
        "is_win_tbl",
        "is_icu_tbl",
        "has_time_cols",
        "validate_tbl_structure",
        "id_vars",
        "index_var",
        "dur_var",
        "meta_vars",
        "data_vars",
        "rbind_lst",
        "rename_cols",
        "rm_cols",
    ),
    "easyicu.table.convert": (
        "reclass_tbl",
        "unclass_tbl",
        "as_col_cfg",
        "as_id_cfg",
        "as_src_cfg",
        "as_tbl_cfg",
        "as_src_tbl",
        "as_ptype",
    ),
    "easyicu.table.id_conversion": (
        "upgrade_id",
        "downgrade_id",
        "change_id",
    ),
    "easyicu.table.meta": (
        "id_var",
        "id_col",
        "index_col",
        "dur_col",
        "dur_unit",
        "data_var",
        "data_col",
        "time_unit",
        "time_step",
        "id_var_opts",
        "default_vars",
    ),
    "easyicu.utils": (
        "round_to",
        "is_val",
        "not_val",
        "is_false",
        "first_elem",
        "last_elem",
        "coalesce",
        "concat",
        "agg_or_na",
        "mean_or_na",
        "sum_or_na",
        "min_or_na",
        "max_or_na",
    ),
    "easyicu.utils.assertions": (
        "assert_that",
        "is_string",
        "is_flag",
        "is_scalar",
        "is_number",
        "is_count",
        "no_na",
        "has_length",
        "has_rows",
        "has_cols",
        "are_in",
        "is_unique",
        "is_sorted",
        "validate_data_frame",
        "validate_id_tbl",
        "validate_ts_tbl",
        "validate_win_tbl",
    ),
    "easyicu.utils.callback_system": (
        "do_callback",
        "do_itm_load",
        "set_callback",
        "prepare_query",
        "add_weight",
        "get_target",
        "set_target",
        "get_itm_var",
    ),
    "easyicu.utils.callback_utils": (
        "transform_fun",
        "binary_op",
        "comp_na",
        "set_val",
        "apply_map",
        "convert_unit",
        "combine_callbacks",
        "fwd_concept",
        "ts_to_win_tbl",
        "locb",
        "aggregate_fun",
        "eicu_age",
        "mimic_age",
        "percent_as_numeric",
        "distribute_amount",
        "distribute_volume_hourly",
        "dex_to_10",
        "mimv_rate",
        "grp_mount_to_rate",
        "grp_amount_to_rate",
        "padded_capped_diff",
    ),
    "easyicu.utils.cli_utils": (
        "is_interactive",
        "progress_init",
        "progress_tick",
        "with_progress",
        "msg_easyicu",
        "warn_easyicu",
        "stop_easyicu",
        "msg_progress",
        "fmt_msg",
        "bullet",
        "big_mark",
        "quote_bt",
        "enbraket",
        "prcnt",
        "ask_yes_no",
        "cli_rule",
    ),
    "easyicu.utils.clinical_utils": (
        "avpu",
        "bmi",
        "gcs",
        "norepi_equiv",
        "supp_o2",
        "urine24",
        "vaso60",
        "vaso_ind",
        "vent_ind",
    ),
    "easyicu.utils.common_utils": (
        "is_true",
        "locf",
        "SeriesUtils",
        "DataFrameUtils",
        "TimeSeriesUtils",
        "ValidationUtils",
        "safe_copy",
        "optimize_dtypes",
    ),
    "easyicu.utils.file_utils": (
        "data_dir",
        "src_data_dir",
        "ensure_dirs",
        "is_dir",
        "dir_exists",
        "dir_create",
        "file_size_format",
        "file_copy_safe",
        "config_paths",
        "get_config",
        "set_config",
        "read_json",
        "write_json",
        "auto_attach_srcs",
        "file_exists",
    ),
    "easyicu.utils.logging_utils": ("configure_logging",),
    "easyicu.utils.unit_conversion": (
        "UnitConverter",
        "celsius_to_fahrenheit",
        "fahrenheit_to_celsius",
        "glucose_mg_to_mmol",
        "glucose_mmol_to_mg",
        "creatinine_mg_to_umol",
        "creatinine_umol_to_mg",
    ),
}

_ALIASES: Final[dict[str, ExportTarget]] = {
    "stay_windows_utils": ("easyicu.io.data_utils", "stay_windows"),
    "id_as_src_env": ("easyicu.io.id_mapping", "as_src_env"),
    "ts_locf": ("easyicu.io.ts_utils", "locf"),
    "ts_locb": ("easyicu.io.ts_utils", "locb"),
    "sirs_score_func": ("easyicu.scores", "sirs_score"),
    "qsofa_score_func": ("easyicu.scores", "qsofa_score"),
    "news_score_func": ("easyicu.scores", "news_score"),
    "mews_score_func": ("easyicu.scores", "mews_score"),
    "table_upgrade_id": ("easyicu.table.id_conversion", "upgrade_id"),
    "table_interval": ("easyicu.table.meta", "interval"),
    "convert_unit_value": ("easyicu.utils.unit_conversion", "convert_unit"),
}


def _build_public_exports() -> dict[str, ExportTarget]:
    exports: dict[str, ExportTarget] = {}
    for module_name, names in _EXPORT_GROUPS.items():
        for name in names:
            if name in exports:
                raise RuntimeError(f"duplicate EasyICU public export: {name}")
            exports[name] = (module_name, name)
    for name, target in _ALIASES.items():
        if name in exports:
            raise RuntimeError(f"duplicate EasyICU public alias: {name}")
        exports[name] = target
    return exports


PUBLIC_EXPORTS: Final[dict[str, ExportTarget]] = _build_public_exports()


# These attributes existed at the package root but were never listed in
# ``__all__``.  Preserve explicit imports for 1.x while keeping them out of the
# supported wildcard surface.
COMPATIBILITY_EXPORTS: Final[dict[str, ExportTarget]] = {
    "DATABASE_ID_CONFIG": ("easyicu.api", "DATABASE_ID_CONFIG"),
    "EXTRACT_MODULES": ("easyicu.api.extraction", "EXTRACT_MODULES"),
    "FilterCriteria": ("easyicu.patient_filter", "FilterCriteria"),
    "LoaderDefaults": ("easyicu.runtime.runtime_defaults", "LoaderDefaults"),
    "ParallelConfig": ("easyicu.runtime.parallel_config", "ParallelConfig"),
    "PatientFilter": ("easyicu.patient_filter", "PatientFilter"),
    "auto_clear_cache_if_enabled": (
        "easyicu.runtime.cache_manager",
        "auto_clear_cache_if_enabled",
    ),
    "calculate_circ_failure_status": (
        "easyicu.scores.circ_failure",
        "calculate_circ_failure_status",
    ),
    "circ_failure_event": (
        "easyicu.scores.circ_failure",
        "circ_failure_event",
    ),
    "cli_concat": ("easyicu.utils.cli_utils", "concat"),
    "extract_all_databases": (
        "easyicu.api.extraction",
        "extract_all_databases",
    ),
    "extract_database": ("easyicu.api.extraction", "extract_database"),
    "filter_patients": ("easyicu.api", "filter_patients"),
    "get_aki_incidence": ("easyicu.scores.kdigo_aki", "get_aki_incidence"),
    "get_all_patient_ids": ("easyicu.api", "get_all_patient_ids"),
    "get_available_memory_mb": (
        "easyicu.runtime.memory_manager",
        "get_available_memory_mb",
    ),
    "get_circ_failure_incidence": (
        "easyicu.scores.circ_failure",
        "get_circ_failure_incidence",
    ),
    "get_cohort_comparison": ("easyicu.api", "get_cohort_comparison"),
    "get_cohort_stats": ("easyicu.api", "get_cohort_stats"),
    "get_global_config": (
        "easyicu.runtime.parallel_config",
        "get_global_config",
    ),
    "get_id_col_for_database": ("easyicu.api", "get_id_col_for_database"),
    "get_parallel_config": (
        "easyicu.runtime.parallel_config",
        "get_parallel_config",
    ),
    "get_patient_table_for_database": (
        "easyicu.api",
        "get_patient_table_for_database",
    ),
    "get_recommended_batch_size": (
        "easyicu.runtime.parallel_config",
        "get_recommended_batch_size",
    ),
    "get_rss_mb": ("easyicu.runtime.memory_manager", "get_rss_mb"),
    "get_smart_parallel_config": ("easyicu.api", "get_smart_parallel_config"),
    "kdigo_creatinine": ("easyicu.scores.kdigo_aki", "kdigo_creatinine"),
    "kdigo_stages": ("easyicu.scores.kdigo_aki", "kdigo_stages"),
    "kdigo_uo": ("easyicu.scores.kdigo_aki", "kdigo_uo"),
    "LACTATE_THRESHOLD": (
        "easyicu.scores.circ_failure",
        "LACTATE_THRESHOLD",
    ),
    "load_circ_failure": (
        "easyicu.scores.circ_failure",
        "load_circ_failure",
    ),
    "load_concepts_filtered": ("easyicu.api", "load_concepts_filtered"),
    "load_kdigo_aki": ("easyicu.scores.kdigo_aki", "load_kdigo_aki"),
    "MAP_THRESHOLD": ("easyicu.scores.circ_failure", "MAP_THRESHOLD"),
    "NOREPI_EPI_LEVEL2_THRESHOLD": (
        "easyicu.scores.circ_failure",
        "NOREPI_EPI_LEVEL2_THRESHOLD",
    ),
    "plot_sepsis_timeline": (
        "easyicu.visualization",
        "plot_sepsis_timeline",
    ),
    "release_memory": ("easyicu.runtime.memory_manager", "release_memory"),
    "reset_global_config": (
        "easyicu.runtime.parallel_config",
        "reset_global_config",
    ),
    "resolve_loader_defaults": (
        "easyicu.runtime.runtime_defaults",
        "resolve_loader_defaults",
    ),
    "setup_data": ("easyicu.io.setup_data", "setup_data"),
    "summarize_aki": ("easyicu.scores.kdigo_aki", "summarize_aki"),
    "summarize_circ_failure": (
        "easyicu.scores.circ_failure",
        "summarize_circ_failure",
    ),
    "validate_circ_failure_data": (
        "easyicu.scores.circ_failure",
        "validate_circ_failure_data",
    ),
}

ALL_EXPORTS: Final[dict[str, ExportTarget]] = {
    **PUBLIC_EXPORTS,
    **COMPATIBILITY_EXPORTS,
}

PUBLIC_NAMES: Final[tuple[str, ...]] = (
    *STABLE_EXPORTS,
    *(name for name in PUBLIC_EXPORTS if name not in STABLE_EXPORTS),
)

if len(PUBLIC_NAMES) != len(set(PUBLIC_NAMES)):
    raise RuntimeError("EasyICU public export names must be unique")
